spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: yusukematsumoto
    password: postgres 
server: 
  servlet:
    context-path: /ex-intermediate